-- Backlog Buddy — Supabase/PostgreSQL migration
-- Run in an EMPTY Supabase project. Browser clients use only the anon key + RLS.
create extension if not exists pgcrypto;

create type public.app_role as enum ('student','editor','admin');
create type public.question_kind as enum ('mcq','short','long','numerical');
create type public.content_status as enum ('draft','review','published','archived');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text, full_name text, role public.app_role not null default 'student',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.universities (id bigint generated by default as identity primary key, name text not null, code text unique not null, region text, active boolean default true);
create table public.courses (id bigint generated by default as identity primary key, name text not null, code text unique not null);
create table public.branches (id bigint generated by default as identity primary key, course_id bigint not null references public.courses(id), name text not null, code text not null, unique(course_id,code));
create table public.regulations (id bigint generated by default as identity primary key, university_id bigint not null references public.universities(id), code text not null, effective_year int, unique(university_id,code));
create table public.semesters (id bigint generated by default as identity primary key, year_no smallint not null check(year_no between 1 and 4), semester_no smallint not null check(semester_no between 1 and 2), label text not null, unique(year_no,semester_no));
create table public.subjects (
  id uuid primary key default gen_random_uuid(), university_id bigint references public.universities(id), branch_id bigint references public.branches(id),
  regulation_id bigint references public.regulations(id), semester_id bigint references public.semesters(id), code text not null, name text not null,
  description text, syllabus jsonb not null default '[]', active boolean default true, created_at timestamptz default now(), unique(university_id,regulation_id,code)
);
create table public.units (id bigint generated by default as identity primary key, subject_id uuid not null references public.subjects(id) on delete cascade, unit_no smallint not null, title text not null, topics jsonb default '[]', unique(subject_id,unit_no));
create table public.questions (
  id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id) on delete cascade, unit_id bigint references public.units(id) on delete cascade,
  body text not null, answer text, question_type public.question_kind not null, marks smallint, difficulty text check(difficulty in ('easy','medium','hard')),
  is_important boolean default false, occurrence_count int default 0, source_note text, created_by uuid references public.profiles(id), status public.content_status default 'draft', created_at timestamptz default now()
);
create table public.question_options (id bigint generated by default as identity primary key, question_id uuid not null references public.questions(id) on delete cascade, body text not null, is_correct boolean default false, explanation text);
create table public.papers (
  id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id), exam_year int not null, exam_month smallint check(exam_month between 1 and 12),
  exam_type text not null, file_url text not null, license_type text not null, source_url text, verified_at timestamptz, uploaded_by uuid references public.profiles(id), created_at timestamptz default now()
);
create table public.materials (id uuid primary key default gen_random_uuid(), subject_id uuid not null references public.subjects(id), unit_id bigint references public.units(id), title text not null, material_type text, file_url text, license_type text not null, status public.content_status default 'draft', created_at timestamptz default now());
create table public.enrollments (user_id uuid references public.profiles(id) on delete cascade, subject_id uuid references public.subjects(id) on delete cascade, is_backlog boolean default true, exam_date date, primary key(user_id,subject_id));
create table public.saved_questions (user_id uuid references public.profiles(id) on delete cascade, question_id uuid references public.questions(id) on delete cascade, saved_at timestamptz default now(), primary key(user_id,question_id));
create table public.practice_tests (id uuid primary key default gen_random_uuid(), subject_id uuid references public.subjects(id), title text not null, config jsonb default '{}', status public.content_status default 'draft');
create table public.practice_attempts (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id), test_id uuid references public.practice_tests(id), score numeric(5,2), answers jsonb not null, started_at timestamptz default now(), completed_at timestamptz);
create table public.study_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id), exam_date date not null, hours_per_day numeric(3,1), generated_plan jsonb not null, created_at timestamptz default now());

create index subject_lookup_idx on public.subjects(university_id,branch_id,regulation_id,semester_id);
create index question_subject_unit_idx on public.questions(subject_id,unit_id);
create index papers_subject_year_idx on public.papers(subject_id,exam_year desc);
create index subject_search_idx on public.subjects using gin(to_tsvector('english',name||' '||coalesce(description,'')));

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,email,full_name) values(new.id,new.email,new.raw_user_meta_data->>'full_name'); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.is_editor() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('editor','admin')); $$;

alter table public.profiles enable row level security;
alter table public.universities enable row level security; alter table public.courses enable row level security; alter table public.branches enable row level security;
alter table public.regulations enable row level security; alter table public.semesters enable row level security; alter table public.subjects enable row level security;
alter table public.units enable row level security; alter table public.questions enable row level security; alter table public.question_options enable row level security;
alter table public.papers enable row level security; alter table public.materials enable row level security; alter table public.enrollments enable row level security;
alter table public.saved_questions enable row level security; alter table public.practice_tests enable row level security; alter table public.practice_attempts enable row level security; alter table public.study_plans enable row level security;

create policy "own profile read" on public.profiles for select using(id=auth.uid() or public.is_editor());
create policy "own profile update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy "public university read" on public.universities for select using(active);
create policy "public course read" on public.courses for select using(true);
create policy "public branch read" on public.branches for select using(true);
create policy "public regulation read" on public.regulations for select using(true);
create policy "public semester read" on public.semesters for select using(true);
create policy "public subject read" on public.subjects for select using(active);
create policy "public unit read" on public.units for select using(true);
create policy "published question read" on public.questions for select using(status='published');
create policy "published options read" on public.question_options for select using(exists(select 1 from public.questions q where q.id=question_id and q.status='published'));
create policy "verified paper read" on public.papers for select using(verified_at is not null);
create policy "published material read" on public.materials for select using(status='published');
create policy "published test read" on public.practice_tests for select using(status='published');

create policy "editor university manage" on public.universities for all using(public.is_editor()) with check(public.is_editor());
create policy "editor course manage" on public.courses for all using(public.is_editor()) with check(public.is_editor());
create policy "editor branch manage" on public.branches for all using(public.is_editor()) with check(public.is_editor());
create policy "editor regulation manage" on public.regulations for all using(public.is_editor()) with check(public.is_editor());
create policy "editor semester manage" on public.semesters for all using(public.is_editor()) with check(public.is_editor());
create policy "editor subject manage" on public.subjects for all using(public.is_editor()) with check(public.is_editor());
create policy "editor unit manage" on public.units for all using(public.is_editor()) with check(public.is_editor());
create policy "editor question manage" on public.questions for all using(public.is_editor()) with check(public.is_editor());
create policy "editor option manage" on public.question_options for all using(public.is_editor()) with check(public.is_editor());
create policy "editor paper manage" on public.papers for all using(public.is_editor()) with check(public.is_editor());
create policy "editor material manage" on public.materials for all using(public.is_editor()) with check(public.is_editor());
create policy "editor test manage" on public.practice_tests for all using(public.is_editor()) with check(public.is_editor());

create policy "own enrollments" on public.enrollments for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own saved questions" on public.saved_questions for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own attempts" on public.practice_attempts for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own study plans" on public.study_plans for all using(user_id=auth.uid()) with check(user_id=auth.uid());

grant usage on schema public to anon, authenticated;
grant select on public.universities,public.courses,public.branches,public.regulations,public.semesters,public.subjects,public.units,public.questions,public.question_options,public.papers,public.materials,public.practice_tests to anon,authenticated;
grant select,update on public.profiles to authenticated;
grant select,insert,update,delete on public.enrollments,public.saved_questions,public.practice_attempts,public.study_plans to authenticated;
grant all on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
